name: Sync From Notion 
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync rewards for testnets
        run: |
          curl --request POST --url 'https://testnet-explorer.meson.fi/api/v1/cron/sync-reward'
      - name: Sync rewards for mainnets
        run: |
          curl --request POST --url 'https://explorer.meson.fi/api/v1/cron/sync-reward'
      - name: Sync free instructions for testnets
        run: |
          curl --request POST --url 'https://testnet-explorer.meson.fi/api/v1/cron/sync-free-instruction'
      - name: Sync free instructions for mainnets
        run: |
          curl --request POST --url 'https://explorer.meson.fi/api/v1/cron/sync-free-instruction'
      - name: Sync Directs for testnets
        run: |
          curl --request POST --url 'https://testnet-explorer.meson.fi/api/v1/cron/sync-free-direct'
      - name: Sync Directs for mainnets
        run: |
          curl --request POST --url 'https://explorer.meson.fi/api/v1/cron/sync-free-direct'